# Generated by Django 6.0 on 2025-12-26 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('image', models.ImageField(upload_to='meme_templates/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('animals', 'Животные'), ('funny', 'Смешные'), ('movies', 'Фильмы'), ('games', 'Игры'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон мема',
                'verbose_name_plural': 'Шаблоны мемов',
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Мой мем', max_length=200, verbose_name='Название')),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memes.memetemplate')),
            ],
            options={
                'verbose_name': 'Мем пользователя',
                'verbose_name_plural': 'Мемы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('font_size', models.IntegerField(default=28)),
                ('font_family', models.CharField(default='Lobster', max_length=50)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('stroke_color', models.CharField(default='#000000', max_length=7)),
                ('position_type', models.CharField(choices=[('inside', 'Внутри'), ('outside', 'Снаружи')], max_length=10)),
                ('position_area', models.CharField(choices=[('top', 'Верх'), ('center', 'Центр'), ('bottom', 'Низ')], max_length=10)),
                ('x', models.FloatField(default=0.5)),
                ('y', models.FloatField(default=0.5)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='memes.meme')),
            ],
        ),
    ]
